name: PR Validate

on:
  pull_request:
    branches:
      - main
      - docker

defaults:
  run:
    shell: bash

jobs:
  full:
    name: PR Validate

    runs-on: ubuntu-latest
    container:
      image: devwithlando/php:8.1-fpm-4

    services:
      database:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      CI: GITHUB_ACTIONS
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER_PASSWORD: drupal
      MYSQL_USER_NAME: drupal
      MYSQL_DATABASE_NAME: drupal
      MYSQL_HOST: database

    steps:
      - name: Prepare environment variables
        run: |
          echo "GITHUB_REF_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "COMPOSER_BIN=$(echo ${GITHUB_WORKSPACE}/vendor/bin)" >> $GITHUB_ENV
          echo "BLT_DIR=$(echo ${GITHUB_WORKSPACE}/vendor/acquia/blt)" >> $GITHUB_ENV
          echo "SCRIPT_DIR=$(echo ${GITHUB_WORKSPACE}/blt/scripts/github-actions)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Composer install
        run: |
          composer validate --no-check-all --ansi
          composer install --no-interaction || composer install --no-interaction || composer install --no-interaction

      - name: Prepare bin executables
        run: |
          ln -s ${GITHUB_WORKSPACE}/vendor/acquia/blt/bin/blt /usr/local/bin/blt
          ln -s ${GITHUB_WORKSPACE}/vendor/drush/drush/drush /usr/local/bin/drush

      - name: Cache dependencies installed with Composer
        id: composer-cache
        run: |
          echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: |
            "${{ steps.composer-cache.outputs.dir }}"
            ~/.drush/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.19.0"
          cache: "npm"

      - name: Setup environment
        run: bash ${SCRIPT_DIR}/setup_env.sh

      - name: Setup app
        run: bash ${SCRIPT_DIR}/setup_app.sh

      - name: Test app
        run: bash ${SCRIPT_DIR}/test_app.sh

      - name: Test Behat
        run: bash ${SCRIPT_DIR}/test_behat.sh
